services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html # Монтируем директорию для WordPress
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Конфигурация Nginx
    depends_on:
      - php
      - mysql
    networks:
      - wordpress-net

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./wordpress:/var/www/html # Монтируем ту же директорию для WordPress
    networks:
      - wordpress-net

  mysql:
    image: mysql:8.0 # Официальный образ MySQL 8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234qwer # Замените на надёжный пароль
      MYSQL_DATABASE: wordpress_sample_db # Имя базы данных WordPress
      MYSQL_USER: wordpress_user # Имя пользователя базы данных WordPress
      MYSQL_PASSWORD: 1234qwer # Пароль пользователя базы данных WordPress
    volumes:
      - db_data:/var/lib/mysql # Сохраняем данные базы данных
    networks:
      - wordpress-net

volumes:
  db_data: # Объявляем том для данных MySQL

networks:
  wordpress-net: # Объявляем сеть для взаимодействия между сервисами